import { getSandbox } from '@cloudflare/sandbox';

interface CmdOutput {
  success: boolean;
  stdout: string;
  stderr: string;
}
// helper to read the outputs from `.exec` results
const getOutput = (res: CmdOutput) => (res.success ? res.stdout : res.stderr);

const EXTRA_SYSTEM =
  'You are an automatic feature-implementer/bug-fixer. ' +
  'Apply all necessary changes to achieve the user request. You must ensure you DO NOT commit the changes, ' +
  'so the pipeline can read the local `git diff` and apply the change upstream.';

async function runTask(
  request: Request,
  env: Env,
  route: '/' | '/sub'
): Promise<Response> {
  try {
    const { repo, task } = await request.json<{
      repo?: string;
      task?: string;
    }>();
    if (!repo || !task) return new Response('invalid body', { status: 400 });

    // get the repo name
    const name = repo.split('/').pop()?.replace(/\.git$/, '') || 'tmp';

    // open sandbox
    const sandbox = getSandbox(env.Sandbox, crypto.randomUUID().slice(0, 8));

    // git clone repo
    await sandbox.gitCheckout(repo, { targetDir: name });

    // wire up auth for the chosen route
    if (route === '/') {
      // CODEX_API_KEY is honored by `codex exec` per-run without touching auth.json
      await sandbox.setEnvVars({ CODEX_API_KEY: env.OPENAI_API_KEY });
    } else {
      // Seed ~/.codex/auth.json from a secret generated by running `codex login`
      // on a trusted machine. https://developers.openai.com/codex/auth/ci-cd-auth
      await sandbox.mkdir('/root/.codex', { recursive: true });
      await sandbox.writeFile('/root/.codex/auth.json', env.CODEX_AUTH_JSON);
    }

    // codex has no `--append-system-prompt` flag, so we prepend our system
    // instructions to the user task.
    const prompt = `${EXTRA_SYSTEM}\n\nTask: ${task.replace(/'/g, "'\\''")}`;

    // kick off codex in non-interactive mode with the workspace-write sandbox
    const logs = getOutput(await sandbox.exec(`codex exec --full-auto '${prompt}'`, { cwd: name }));
    const diff = getOutput(await sandbox.exec('git diff', { cwd: name }));
    return Response.json({ logs, diff });
  } catch (err) {
    if (err instanceof SyntaxError) return new Response('invalid body', { status: 400 });
    throw err;
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    if (request.method !== 'POST') return new Response('not found', { status: 404 });

    const { pathname } = new URL(request.url);

    if (pathname === '/') {
      // API key route (pay-per-token)
      return runTask(request, env, '/');
    }

    if (pathname === '/sub') {
      // ChatGPT subscription route — get the auth bundle by running
      // `codex login` locally and copying ~/.codex/auth.json into CODEX_AUTH_JSON
      return runTask(request, env, '/sub');
    }

    return new Response('not found', { status: 404 });
  }
};

export { Sandbox } from '@cloudflare/sandbox';
